# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=800)),
                ('type_of_appointment', models.CharField(max_length=100)),
                ('reason_for_appointment', models.TextField(max_length=2000)),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('birthday', models.DateField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=b'')),
                ('PASI', models.IntegerField(blank=True)),
                ('last_doctor_appointment', models.DateField(blank=True)),
                ('date_registered', models.DateField()),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('isMentor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_address', models.CharField(max_length=500)),
                ('profile_picture', models.ImageField(upload_to=b'')),
                ('distance_from_user', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('date_taken', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('redness', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psoriassist.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('date_prescribed', models.DateField()),
                ('expiration_date', models.DateField()),
                ('dosage', models.CharField(max_length=2000)),
                ('other_info', models.TextField(max_length=2000)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psoriassist.Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psoriassist.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='MentalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('mood', models.IntegerField()),
                ('date_taken', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psoriassist.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_date', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerConvo', to='psoriassist.AppUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialiseConvo', to='psoriassist.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=0)),
                ('medication', models.ManyToManyField(to='psoriassist.Medication')),
                ('user', models.ManyToManyField(to='psoriassist.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='psoriassist.Doctor'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='mentoree',
            field=models.ManyToManyField(blank=True, to='psoriassist.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(to='psoriassist.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ManyToManyField(to='psoriassist.AppUser'),
        ),
    ]
