# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
