# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='isCurrent',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
