# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='doctor',
            field=models.ManyToManyField(null=True, to='psoriassist.Doctor'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_doctor_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='mentoree',
            field=models.ManyToManyField(null=True, to='psoriassist.AppUser'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
