# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0002_medication_iscurrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='medication',
        ),
        migrations.AddField(
            model_name='rating',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psoriassist.Medication'),
            preserve_default=False,
        ),
    ]
