# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0002_auto_20160307_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_registered',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='doctor',
            field=models.ManyToManyField(to='psoriassist.Doctor'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='mentoree',
            field=models.ManyToManyField(to='psoriassist.AppUser'),
        ),
    ]
