# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0002_auto_20160308_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='redness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='scale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='thickness',
            field=models.IntegerField(null=True),
        ),
    ]
