# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0003_auto_20160309_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='lesion_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psoriassist.LesionSection'),
        ),
    ]
