# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0004_auto_20160313_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
