# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0005_auto_20160313_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.BooleanField()),
                ('message_content', models.TextField(max_length=2000)),
                ('date_sent', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psoriassist.AppUser')),
            ],
        ),
    ]
