# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0009_remove_computerconversation_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerconversation',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
