# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0010_auto_20160315_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerconversation',
            name='sender',
            field=models.CharField(max_length=1000),
        ),
    ]
