# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0011_auto_20160315_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerconversation',
            name='topic',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
