# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0012_computerconversation_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerconversation',
            name='topic',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
