# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0013_auto_20160315_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerconversation',
            name='topic',
        ),
        migrations.AddField(
            model_name='computerconversation',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
