# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0015_auto_20160316_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerconversation',
            name='sender',
        ),
    ]
