# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psoriassist', '0016_remove_computerconversation_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerconversation',
            name='computer_message',
        ),
        migrations.RemoveField(
            model_name='computerconversation',
            name='user_message',
        ),
    ]
